-- AlterEnum
ALTER TYPE "AuditEvent" ADD VALUE IF NOT EXISTS 'SIGNATURE_ARCHIVED';
ALTER TYPE "AuditEvent" ADD VALUE IF NOT EXISTS 'SIGNATURE_RESTORED';
ALTER TYPE "AuditEvent" ADD VALUE IF NOT EXISTS 'SIGNATURE_DELETED';
